### ISSUE TITLE
Review OBO artefact (WBBT)

### ISSUE THREAD

**Issue by matentzn** [obophenotype/c-elegans-gross-anatomy-ontology#1]
Review the [OBO release artefact](https://github.com/obophenotype/c-elegans-gross-anatomy-ontology/blob/master/wbbt.obo). You should download it, then download the old [wbbt.obo](https://raw.githubusercontent.com/obophenotype/Wao/master/WBbt.obo) then diff them (for example with the command line or whatever other tool you use.

There will be differences, that is for sure! The question is whether they are acceptable. We will talk about your findings during the next meeting.

**Comment by balhoff** [comment]
https://stars-app.renci.org/owldiff/diff?left=https%3A%2F%2Fraw.githubusercontent.com%2Fobophenotype%2FWao%2Fmaster%2FWBbt.obo&right=https%3A%2F%2Fgithub.com%2Fobophenotype%2Fc-elegans-gross-anatomy-ontology%2Fraw%2Fmaster%2Fwbbt.obo&loadimports=true

**Comment by matentzn** [comment]
OH MY GOD (@balhoff) WHAT AMAZING THING IS! :D :D

**Comment by matentzn** [comment]
(So @chris-grove, you should do both balhoff diff and inspect the physical differences, because we care also about syntactic differences in the exact way the obo file is arranged. But THAT DIFF is amazing. Thank you than you!)

**Comment by balhoff** [comment]
@matentzn make your own links here: https://stars-app.renci.org/owldiff/

**Comment by chris-grove** [comment]
I'm going to sign off on this that the new file is satisfactory.

**Comment by chris-grove** [comment]
@raymond91125  Please review and reopen if you deem necessary
